[package]
name = "bitty"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glow = "0.10.0"
sdl2 = "0.34.5"
bytemuck = "1.7.0"